services:
  devcontainer:
    build:
      context: .
    container_name: devcontainer-app
    volumes:
      - ..:/workspace:cached
      - gohome:/home/dev/go:cached
      - app-node-modules:/workspaces/frontend/node_modules
    command: sleep infinity
    depends_on:
      - db

  caddy:
    image: caddy:2
    container_name: caddy-local
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile
    env_file: [ ../.env.local ]
    ports:
      - "80:80"
    depends_on:
      - devcontainer

  db:
    image: postgres:15
    container_name: db-local
    env_file: [ ../.env.local ]
    ports:
      - "5432:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
      - ../ansible/vps/docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  app-node-modules:
  pgdata-dev:
  gohome:
