services:
  devcontainer:
    build:
      context: .
    container_name: devcontainer-app
    volumes:
      - ..:/workspace:cached
      - gohome:/home/dev/go:cached
      - app-node-modules:/workspaces/frontend/node_modules
    command: sleep infinity
    depends_on:
      - db

  caddy:
    image: caddy:2
    container_name: caddy-local
    volumes:
      - ../docker/caddy/Caddyfile.local:/etc/caddy/Caddyfile
    environment:
      - BACKEND_PORT=8080
      - FRONTEND_PORT=3001
    ports:
      - "80:80"
    depends_on:
      - devcontainer

  db:
    image: postgres:15
    container_name: db-local
    env_file: [../.env]
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mental
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mental
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

volumes:
  app-node-modules:
  pgdata-dev:
  gohome:
