- name: Deploy Docker stack for mental project
  hosts: all
  become: true

  tasks:
    - name: ディレクトリ {{ app_dir }}/files の存在確認
      file:
        path: "{{ app_dir }}/files"
        state: directory
        owner: "{{ ansible_user }}"
        group: docker
        mode: "0755"

    - name: compose関連ファイルを同期
      vars:
        ansible_root: "{{ playbook_dir }}/.."
      synchronize:
        src: "{{ ansible_root }}/files/"
        dest: "{{ app_dir }}/files/"
        recursive: yes
        checksum: yes
        delete: yes
        owner: no
        group: no
        perms: no
      register: compose_sync_result

    - name: compose関連ファイルの権限設定
      shell: |
        chown -R {{ ansible_user }}:docker {{ app_dir }}/files
        find {{ app_dir }}/files -type d -exec chmod 0755 {} \;
        find {{ app_dir }}/files -type f -exec chmod 0644 {} \;
      when: compose_sync_result.changed

    - name: ディレクトリ {{ app_dir }}/docker の存在確認
      file:
        path: "{{ app_dir }}/docker"
        state: directory
        owner: "{{ ansible_user }}"
        group: docker
        mode: "0755"

    - name: Docker 関連の設定ファイルを同期
      vars:
        project_root: "{{ playbook_dir }}/../.."
      synchronize:
        src: "{{ project_root }}/docker/"
        dest: "{{ app_dir }}/docker/"
        delete: yes
        recursive: yes
        checksum: yes
        owner: no
        group: no
        perms: no
      notify:
        - reload stack
      register: docker_sync_result

    - name: Docker設定ファイルの権限設定
      shell: |
        chown -R {{ ansible_user }}:docker {{ app_dir }}/docker
        find {{ app_dir }}/docker -type d -exec chmod 0755 {} \;
        find {{ app_dir }}/docker -type f -exec chmod 0644 {} \;
      when: docker_sync_result.changed

    - name: secrets ディレクトリの存在確認
      stat:
        path: "{{ playbook_dir }}/../../secrets"
      register: secrets_dir
      delegate_to: localhost
      become: false

    - name: ディレクトリ {{ app_dir }}/secrets の存在確認
      file:
        path: "{{ app_dir }}/secrets"
        state: directory
        owner: "{{ ansible_user }}"
        group: docker
        mode: "0755"
      when: secrets_dir.stat.exists

    - name: secrets ディレクトリを同期
      vars:
        project_root: "{{ playbook_dir }}/../.."
      synchronize:
        src: "{{ project_root }}/secrets/"
        dest: "{{ app_dir }}/secrets/"
        delete: yes
        recursive: yes
        checksum: yes
        owner: no
        group: no
        perms: no
      register: secrets_result
      when: secrets_dir.stat.exists

    - name: secrets ファイルの権限設定
      shell: |
        chown -R {{ ansible_user }}:docker {{ app_dir }}/secrets
        find {{ app_dir }}/secrets -type d -exec chmod 0755 {} \;
        find {{ app_dir }}/secrets -type f -exec chmod 0644 {} \;
      when: secrets_result.changed

  handlers:
    - name: reload stack
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}/files"
        project_name: "mental"
        state: present           # pull + up -d
        pull: missing
        recreate: auto
        remove_orphans: false
        services:
          - backend
          - frontend
          - backend-staging
          - frontend-staging
          - caddy
