- name: Install essential packages and tools
  hosts: all
  become: true

  tasks:
    - name: apt update を実行
      apt:
        update_cache: yes

    - name: 便利ツール追加
      apt:
        name:
          - git
          - curl
          - htop
          - unzip
        state: present

    - name: Docker
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Docker Compose (v2 as plugin)
      apt:
        name: docker-compose-plugin
        state: present

    - name: ansible ユーザを docker グループに追加
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: docker の自動起動を設定して起動
      systemd:
        name: docker
        enabled: true
        state: started

  roles:
    - role: artis3n.tailscale
      vars:
        verbose: true
        tailscale_authkey: "{{ taliscale_key }}"
        tailscale_tags:
          - server
        tailscale_oauth_preauthorized: true
        tailscale_oauth_ephemeral: true
        tailscale_args: "--ssh"
