# playbooks/maintenance-security.yml
- name: Configure automatic maintenance and security updates
  hosts: all
  become: true

  tasks:
    - name: Fail2Ban 追加
      apt:
        name: fail2ban
        state: present

    - name: Fail2Ban の自動起動を設定して起動
      systemd:
        name: fail2ban
        enabled: true
        state: started

    - name: unattended-upgrades 追加
      apt:
        name: unattended-upgrades
        state: present

    - name: 自動適用の間隔設定
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";

    - name: 不要なパッケージの自動削除
      apt:
        autoremove: yes

    - name: 自動クリーンアップの設定
      apt:
        autoclean: yes

    - name: Install needrestart for service restarts
      apt:
        name: needrestart
        state: present

    - name: Configure cron job for apt cleanups
      cron:
        name: "weekly apt cleanup"
        weekday: "0"
        hour: "3"
        job: "apt autoremove -y && apt autoclean -y"
