
name: Deploy to Staging
on:
  push:
    branches: [devel]

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      image_tag: staging
      compose_services: backend-staging frontend-staging
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      VPS_PORT: ${{ secrets.VPS_PORT }}
      VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
