
name: Deploy to Production
on:
  push:
    branches: [main]

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      image_tag: prod
      compose_services: backend frontend
    permissions: { contents: read, packages: write }
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      VPS_PORT: ${{ secrets.VPS_PORT }}
      VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
