name: build-and-deploy-staging

on:
  push:
    branches: [devel]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/mrtgm/mental-

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }

    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build + push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ env.IMAGE_PREFIX }}frontend:staging
          ${{ env.IMAGE_PREFIX }}frontend:staging-${{ github.sha }}

    - name: Build + push backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ env.IMAGE_PREFIX }}backend:staging
          ${{ env.IMAGE_PREFIX }}backend:staging-${{ github.sha }}

    - name: Apply Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ansible/playbooks/deploy-stack.yml
        key: ${{ secrets.VPS_SSH_KEY }}
        vault_password: ${{ secrets.VAULT_PASSWORD }}
        inventory: |
          [vps]
          ${{ secrets.VPS_HOST }} ansible_user=${{ secrets.VPS_USER }} ansible_port=${{ secrets.VPS_PORT }} ansible_become=true
        options: |
          --extra-vars "@ansible/inventory/group_vars/vps.yml"
          --extra-vars "ansible_ssh_private_key_file=.ansible_key"

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1
      with:
        host:   ${{ secrets.VPS_HOST }}
        user:   ${{ secrets.VPS_USER }}
        key:    ${{ secrets.VPS_SSH_KEY }}
        port:   ${{ secrets.VPS_PORT }}
        script: |
          cd /opt/mental
          docker compose pull backend-staging frontend-staging
          docker compose up -d --wait --no-deps \
                backend-staging frontend-staging
          docker image prune -af --filter "until=240h"
